// Default settings mirrored from upstream defaultSettings in storeTypes.ts
// https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip

import type { SettingsType } from '../types/settings.js';

export const defaultSettings: SettingsType = {
  Amazon: {
    skipIntro: true,
    skipCredits: true,
    watchCredits: false,
    selfAd: true,
    skipAd: true,
    speedSlider: true,
    filterPaid: false,
    continuePosition: true,
    showRating: true,
    xray: false,
    improveUI: true,
  },
  Netflix: {
    skipIntro: true,
    skipRecap: true,
    skipCredits: true,
    watchCredits: false,
    skipBlocked: false,
    skipAd: true,
    speedSlider: true,
    profile: false,
    showRating: true,
    removeGames: false,
    hideTitles: false,
  },
  Disney: {
    skipIntro: true,
    skipCredits: true,
    watchCredits: false,
    skipAd: true,
    speedSlider: true,
    showRating: true,
    selfAd: true,
    hideTitles: false,
  },
  Crunchyroll: {
    skipIntro: true,
    skipCredits: true,
    skipAfterCredits: true,
    speedSlider: true,
    releaseCalendar: true,
    profile: false,
    bigPlayer: false,
    filterQueued: false,
    dubLanguage: 'en-US',
    filterDuplicates: false,
  },
  HBO: {
    skipIntro: true,
    skipCredits: true,
    watchCredits: false,
    speedSlider: true,
    showRating: true,
  },
  Paramount: {
    skipIntro: true,
    skipCredits: true,
    watchCredits: false,
    speedSlider: true,
    showRating: true,
    skipAd: true,
  },
  Video: {
    playOnFullScreen: false,
    epilepsy: false,
    userAgent: false,
    doubleClick: true,
    scrollVolume: true,
    showYear: true,
    dimLowRatings: false,
  },
  General: {
    sliderSteps: 0.25,
    sliderMin: 0.25,
    sliderMax: 4,
    Crunchyroll_skipTimeout: 5,
    RatingThresholds: [
      { color: '#ff0000', value: 4 },
      { color: '#ff8000', value: 6 },
      { color: '#ffff00', value: 7.5 },
      { color: '#00cc00', value: 10 },
    ],
  },
};
